### ISSUE TITLE
getting error while restoring state from file which contains subprocess

### ISSUE THREAD

**Issue by imrushi** [sartography/SpiffWorkflow#276]
Hi, I am getting the below error when I am restoring the state from a file containing a subprocess. Normally it is working fine without a subprocess.

I was using/referring [spiff-cli](https://github.com/sartography/spiff-example-cli) example.
and this [doc](https://spiffworkflow.readthedocs.io/en/latest/bpmn/events.html#escalation-events)

```
$ ./run.py -p order_product -d bpmn/product_prices.dmn bpmn/shipping_costs.dmn -b bpmn/events.bpmn bpmn/call_activity.bpmn -r test6.json
Traceback (most recent call last):
  File "D:\spiff-example-cli\run.py", line 82, in <module>
    wf = serializer.deserialize_json(state.read())
  File "D:\spiff-example-cli\venv\lib\site-packages\SpiffWorkflow\bpmn\serializer\workflow.py", line 143, in deserialize_json
    return self.workflow_from_dict(dct, read_only)
_1
    subprocesses[sp]['tasks'][task_id]['parent'] = None
KeyError: 'data
```

**Comment by essweine** [comment]
I'll look into this.
