### ISSUE TITLE
[Need Help] Custom task example doesn't work

### ISSUE THREAD

**Issue by cuserdzy** [sartography/SpiffWorkflow#313]
Hi team, 

I tried the [example](https://spiffworkflow.readthedocs.io/en/v1.2.0/non-bpmn/custom-tasks/index.html?highlight=custom#implementing-custom-tasks) from official document, but once I ran, it throw exception:

```shell
Traceback (most recent call last):
  File "test_flow.py", line 15, in <module>
    workflow = Workflow(spec)
  File "/***/lib/python3.7/site-packages/SpiffWorkflow/workflow.py", line 77, in __init__
    self.spec.start._predict(start)
  File "/***/python3.7/site-packages/SpiffWorkflow/specs/base.py", line 252, in _predict
    self._predict_hook(my_task)
  File "/***/lib/python3.7/site-packages/SpiffWorkflow/specs/base.py", line 269, in _predict_hook
    my_task._sync_children(self.outputs, best_state)
  File "/***/lib/python3.7/site-packages/SpiffWorkflow/task.py", line 565, in _sync_children
    self._add_child(task_spec, state)
  File "/***/lib/python3.7/site-packages/SpiffWorkflow/task.py", line 475, in _add_child
    raise ValueError(self, '_add_child() requires a TaskSpec')
ValueError: (<Task object (Start) in state FUTURE at 0x7fdf5f2e0590>, '_add_child() requires a TaskSpec')
```

The code are directly copied from document.

serializer.py
```python
from SpiffWorkflow.serializer.json import JSONSerializer

from strike import NuclearStrike


class NuclearSerializer(JSONSerializer):
    def serialize_nuclear_strike(self, task_spec):
        return self.serialize_task_spec(task_spec)

    def deserialize_nuclear_strike(self, wf_spec, s_state):
        spec = NuclearStrike(wf_spec, s_state['name'])
        self.deserialize_task_spec(wf_spec, s_state, spec=spec)
        return spec
```

strike.py
```python
from SpiffWorkflow.specs import Simple


class NuclearStrike(Simple):
    def _on_complete_hook(self, my_task):
        print((self.my_variable, "sent!"))

    def serialize(self, serializer):
        return serializer.serialize_nuclear_strike(self)

    @classmethod
    def deserialize(self, serializer, wf_spec, s_state):
        return serializer.deserialize_nuclear_strike(wf_spec, s_state)

```

test_flow.py
```python

from SpiffWorkflow.workflow import Workflow
from SpiffWorkflow.specs import WorkflowSpec


from serializer import NuclearSerializer


if __name__ == '__main__':
    with open('test_spec.json') as fp:
        task_specs_json = fp.read()
    custom_serializer = NuclearSerializer()
    spec = WorkflowSpec.deserialize(custom_serializer, task_specs_json)

    workflow = Workflow(spec)
    workflow.complete_all()

```

test_spec.json
```
{
  "task_specs": {
      "Start": {
          "class": "SpiffWorkflow.specs.StartTask.StartTask",
          "manual": false,
          "outputs": [
              "general"
          ]
      },
      "general": {
          "class": "SpiffWorkflow.specs.ExclusiveChoice.ExclusiveChoice",
          "name": "general",
          "manual": true,
          "inputs": [
              "Start"
          ],
          "outputs": [
              "workflow_aborted",
              "president"
          ],
          "choice": null,
          "default_task_spec": "workflow_aborted",
          "cond_task_specs": [
              [
                  [
                      "SpiffWorkflow.operators.Equal",
                      [
                          [
                              "Attrib",
                              "confirmation"
                          ],
                          [
                              "value",
                              "yes"
                          ]
                      ]
                  ],
                  "president"
              ]
          ]
      },
      "president": {
          "class": "SpiffWorkflow.specs.ExclusiveChoice.ExclusiveChoice",
          "name": "president",
          "manual": true,
          "inputs": [
              "general"
          ],
          "outputs": [
              "workflow_aborted",
              "nuclear_strike"
          ],
          "choice": null,
          "default_task_spec": "workflow_aborted",
          "cond_task_specs": [
              [
                  [
                      "SpiffWorkflow.operators.Equal",
                      [
                          [
                              "Attrib",
                              "confirmation"
                          ],
                          [
                              "value",
                              "yes"
                          ]
                      ]
                  ],
                  "nuclear_strike"
              ]
          ]
      },
      "nuclear_strike": {
          "class": "strike.NuclearStrike",
          "name": "nuclear_strike",
          "inputs": [
              "president"
          ]
      },
      "workflow_aborted": {
          "class": "SpiffWorkflow.specs.Cancel.Cancel",
          "name": "workflow_aborted",
          "inputs": [
              "general",
              "president"
          ]
      }
  },
  "description": "",
  "file": null,
  "name": ""
}
```

I will be very grateful if you ccould help on this!

**Comment by cuserdzy** [comment]
Test on both version 1.2.1 and 1.2.0 in clean python virtual environment

**Comment by essweine** [comment]
There seems to be a bug here.  We have a test that supposedly runs this example, but there is clearly something wrong with the test (which passes, but should now), as well as the serializer.  I will look into this.

**Comment by cuserdzy** [comment]
Hi @essweine, I check the latest source code and found the issue(because the latest version 1.2.1 on pip is old and it seems some internal logic and APIs already changed in current source code).

While deserialization, the outputs and inputs result are incorrect, as you can see the elements in outputs array are all `None`
```shell
Start [None]
general [None, None]
president [None, None]
nuclear_strike []
workflow_aborted []
```

The array should be a list of TaskSpec objects, but while try to deserialize each task spec, the code use id to get the task spec object, but no id is defined in json, so get `None` here.

The code: https://github.com/sartography/SpiffWorkflow/blob/3c3345c85dd7f3b7112ad04aaa6487abbd2e9414/SpiffWorkflow/serializer/dict.py#L521

I can use a simple workaround to get task spec object by use 'id' and 'name' one by one, but it still confused to mix 'id' and 'name' in the code and use both of them without check their value.

**Comment by essweine** [comment]
Glad you found a workaround, and I'm sorry I wasn't able to respond sooner.  

The confusion seems to be caused by some bpmn-related changes made quite some time ago.  I believe this change:
https://github.com/sartography/SpiffWorkflow/commit/fc3deb62136304edcf69a9490e16c951cac6de5c
introduced the issue.  Prior to that the serializer looked for tasks by name.

As I noted above, we have a test that purportedly runs this code, but it always passes for some reason when it clearly should not, so that's why we never noticed this problem before I suppose.

I am going to try to clean this up (making the test work right, and fixing the serializer).  Thanks for reporting!

**Comment by essweine** [comment]
@cuserdzy I've opened a PR that addresses this issue https://github.com/sartography/SpiffWorkflow/pull/317

**Comment by cuserdzy** [comment]
Sorry for the late response.
Thank you very much it works well now!
