### ISSUE TITLE
SpiffWorkflow.bpmn.parser.ValidationException.ValidationException: No DMN Diagram available with id "None", Available DMN ids are: product_prices.

### ISSUE THREAD

**Issue by sumitgpl** [sartography/SpiffWorkflow#354]
Trying to execute below command and getting error...

`python spiff-bpmn-runner.py -p order_product -b bpmn/task_types.bpmn -d bpmn/tutorial/product_prices.dmn`

seems like Business rule task looking for some extension and default cumunda Business rule task not have.

full traceback dtls :-  
Traceback (most recent call last):
  File "D:\bitsflowtech\ProcessFlow\bkp\spiff-example-cli-main\run_bpmn.py", line 147, in <module>
    runner.parse(args.process or args.collaboration, args.bpmn, args.dmn, args.collaboration is not None)
  File "D:\bitsflowtech\ProcessFlow\bkp\spiff-example-cli-main\runner\runner.py", line 26, in parse
    top_level = self.parser.get_spec(name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\BpmnParser.py", line 329, in get_spec
    return parser.get_spec()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\ProcessParser.py", line 149, in get_spec
    self._parse()
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\ProcessParser.py", line 138, in _parse
    self.parse_node(node)
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\ProcessParser.py", line 111, in parse_node
    task_spec = np.parse_node()
                ^^^^^^^^^^^^^^^
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\TaskParser.py", line 235, in parse_node
    raise ve
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\TaskParser.py", line 214, in parse_node
    c = self.process_parser.parse_node(target_node)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\ProcessParser.py", line 111, in parse_node
    task_spec = np.parse_node()
                ^^^^^^^^^^^^^^^
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\TaskParser.py", line 235, in parse_node
    raise ve
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\TaskParser.py", line 214, in parse_node
    c = self.process_parser.parse_node(target_node)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\ProcessParser.py", line 111, in parse_node
    task_spec = np.parse_node()
                ^^^^^^^^^^^^^^^
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\TaskParser.py", line 235, in parse_node
    raise ve
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\bpmn\parser\TaskParser.py", line 179, in parse_node
    self.task = self.create_task()
                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\spiff\parser\task_spec.py", line 198, in create_task
    dmnEngine=self.process_parser.parser.get_engine(decision_ref, self.node),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smdub\.conda\envs\processflow\Lib\site-packages\SpiffWorkflow\dmn\parser\BpmnDmnParser.py", line 52, in get_engine
    raise ValidationException(
SpiffWorkflow.bpmn.parser.ValidationException.ValidationException: No DMN Diagram available with id "None", Available DMN ids are: product_prices

**Comment by essweine** [comment]
Running `./spiff-bpmn-runner.py -p order_product -b bpmn/tutorial/task_types.bpmn -d bpmn/tutorial/product_prices.dmn` (note error in the path of your provided command) works fine for me.

It looks like you've created your own runner based on `spiff-bpmn-runner.py` which passes in a parser that expects spiffworkflow extensions on task specs, which are in fact different from camunda extensions.  If you want to use our (limited) support for camunda, see `camunda-bpmn-runner.py` for an example of how to create a parser that knows about those extensions.

Also, if you continue to have trouble, please open issues relating to the example code in https://github.com/sartography/spiff-example-cli
