### ISSUE TITLE
Some errors while running test suite on Windows

### ISSUE THREAD

**Issue by mrkafk** [sartography/SpiffWorkflow#41]
tests/SpiffWorkflow/run_suite.py, line 72 also needed fixing:

```
 name   = name.lstrip('.').lstrip(os.sep).replace(os.sep, '.')
```

Traceback:

```
C:\ACME\Dev\projects\SpiffWorkflow-master\ve\Scripts\python.exe C:/ACME/Dev/projects/SpiffWorkflow-master_GITHUB2/tests/SpiffWorkflow/run_suite.py
WARNING: Celery not found, not all tests are running!
testPattern (PatternTest.PatternTest) ... C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\acyclic_synchronizing_merge.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\arbitrary_cycles.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\blocking_discriminator.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\blocking_partial_join.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\cancelling_discriminator.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\cancelling_partial_join.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\cancelling_partial_join_for_multi_instance.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\cancel_case.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\cancel_multi_instance_task.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\cancel_region.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\cancel_task.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\complete_multiple_instance_activity.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\critical_section.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\deferred_choice.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\dynamic_partial_join_for_multi_instance.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\exclusive_choice.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\explicit_termination.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\generalized_and_join.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\general_synchronizing_merge.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\implicit_termination.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\interleaved_parallel_routing.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\interleaved_routing.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\milestone.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\multi_choice.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\multi_instance_without_a_priori.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\multi_instance_without_synch.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\multi_instance_with_a_priori_design_time_knowledge.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\multi_instance_with_a_priori_run_time_knowledge.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\multi_merge.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\parallel_split.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\persistent_trigger.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\recursion.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\sequence.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\simple_merge.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\static_partial_join_for_multi_instance.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\structured_discriminator.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\structured_partial_join.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\structured_synchronizing_merge.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\subworkflow_to_join.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\subworkflow_to_join_inner.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\synchronization.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\thread_merge.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\thread_split.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\transient_trigger.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/data\block_data.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/data\block_data_inner.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/data\block_to_subworkflow.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/data\block_to_subworkflow_inner.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/data\subworkflow_to_block.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/data\subworkflow_to_block_inner.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/data\task_data.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/data\task_to_task.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff\workflow1.py
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff\workflow1.xml
ok
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff\__init__.py
testDeserialization (PersistSmallWorkflowTest.PersistSmallWorkflowTest) ... ok
testDictionarySerializer (PersistSmallWorkflowTest.PersistSmallWorkflowTest) ... ok
testTree (TaskTest.TaskTest) ... ok
testBeginWorkflowStepByStep (WorkflowTest.WorkflowTest) ... ok
testConstructor (WorkflowTest.WorkflowTest) ... ok
testRunThroughCancel (bpmn.ActionManagementTest.ActionManagementTest) ... ok
testRunThroughCancelAfterApproved (bpmn.ActionManagementTest.ActionManagementTest) ... ok
testRunThroughCancelAfterWorkStarted (bpmn.ActionManagementTest.ActionManagementTest) ... ok
testRunThroughHappy (bpmn.ActionManagementTest.ActionManagementTest) ... ok
testRunThroughOverdue (bpmn.ActionManagementTest.ActionManagementTest) ... ok
testReadonlyWaiting (bpmn.ApprovalsTest.ApprovalsTest) ... ok
testRunThroughHappy (bpmn.ApprovalsTest.ApprovalsTest) ... ok
testRunThroughHappyOtherOrders (bpmn.ApprovalsTest.ApprovalsTest) ... ok
testSaveRestore (bpmn.ApprovalsTest.ApprovalsTest) ... ok
testSaveRestoreWaiting (bpmn.ApprovalsTest.ApprovalsTest) ... ok
testDisconnectedBoundaryEvent (bpmn.InvalidWorkflowsTest.InvalidWorkflowsTest) ... ok
testMultipleStartEvents (bpmn.InvalidWorkflowsTest.InvalidWorkflowsTest) ... ok
testNoStartEvent (bpmn.InvalidWorkflowsTest.InvalidWorkflowsTest) ... ok
testRecursiveSubprocesses (bpmn.InvalidWorkflowsTest.InvalidWorkflowsTest) ... ERROR:SpiffWorkflow.bpmn.parser.TaskParser:NotImplementedError('Recursive call Activities are not supported.',)
Traceback (most recent call last):
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\..\..\SpiffWorkflow\bpmn\parser\TaskParser.py", line 59, in parse_node
    self.task = self.create_task()
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\..\..\SpiffWorkflow\bpmn\parser\task_parsers.py", line 110, in create_task
    wf_spec = self.get_subprocess_parser().get_spec()
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\..\..\SpiffWorkflow\bpmn\parser\ProcessParser.py", line 113, in get_spec
    raise NotImplementedError('Recursive call Activities are not supported.')
NotImplementedError: Recursive call Activities are not supported.

ok
testSubprocessNotFound (bpmn.InvalidWorkflowsTest.InvalidWorkflowsTest) ... ok
testUnsupportedTask (bpmn.InvalidWorkflowsTest.InvalidWorkflowsTest) ... ok
testRunThroughHappySaveAndRestore (bpmn.MessageInterruptsSpTest.MessageInterruptsSpTest) ... ok
testRunThroughInterruptSaveAndRestore (bpmn.MessageInterruptsSpTest.MessageInterruptsSpTest) ... ok
testRunThroughHappy (bpmn.MessageInterruptsTest.MessageInterruptsTest) ... ok
testRunThroughHappySaveAndRestore (bpmn.MessageInterruptsTest.MessageInterruptsTest) ... ok
testRunThroughMessageInterrupt (bpmn.MessageInterruptsTest.MessageInterruptsTest) ... ok
testRunThroughMessageInterruptSaveAndRestore (bpmn.MessageInterruptsTest.MessageInterruptsTest) ... ok
testRunThroughHappySaveAndRestore (bpmn.MessageNonInterruptsSpTest.MessageNonInterruptsSpTest) ... ok
testRunThroughMessageOrder2SaveAndRestore (bpmn.MessageNonInterruptsSpTest.MessageNonInterruptsSpTest) ... ok
testRunThroughMessageOrder3SaveAndRestore (bpmn.MessageNonInterruptsSpTest.MessageNonInterruptsSpTest) ... ok
testRunThroughMessageSaveAndRestore (bpmn.MessageNonInterruptsSpTest.MessageNonInterruptsSpTest) ... ok
testRunThroughHappy (bpmn.MessageNonInterruptTest.MessageNonInterruptTest) ... ok
testRunThroughHappySaveAndRestore (bpmn.MessageNonInterruptTest.MessageNonInterruptTest) ... ok
testRunThroughMessageInterrupt (bpmn.MessageNonInterruptTest.MessageNonInterruptTest) ... ok
testRunThroughMessageInterruptOtherOrder (bpmn.MessageNonInterruptTest.MessageNonInterruptTest) ... ok
testRunThroughMessageInterruptOtherOrderSaveAndRestore (bpmn.MessageNonInterruptTest.MessageNonInterruptTest) ... ok
testRunThroughMessageInterruptSaveAndRestore (bpmn.MessageNonInterruptTest.MessageNonInterruptTest) ... ok
testRunThroughHappy (bpmn.MessagesTest.MessagesTest) ... ok
testRunThroughSaveAndRestore (bpmn.MessagesTest.MessagesTest) ... ok
testNoFirstThenThread1 (bpmn.ParallelTest.ParallelJoinLongInclusiveTest) ... ok
testRunThroughAlternating (bpmn.ParallelTest.ParallelJoinLongInclusiveTest) ... ok
testRunThroughThread1First (bpmn.ParallelTest.ParallelJoinLongInclusiveTest) ... ok
testRunThroughThread1FirstThenNo (bpmn.ParallelTest.ParallelJoinLongInclusiveTest) ... ok
testRunThroughAlternating (bpmn.ParallelTest.ParallelJoinLongTest) ... ok
testRunThroughThread1First (bpmn.ParallelTest.ParallelJoinLongTest) ... ok
test1 (bpmn.ParallelTest.ParallelLoopingAfterJoinTest) ... ok
test2 (bpmn.ParallelTest.ParallelLoopingAfterJoinTest) ... ok
test1 (bpmn.ParallelTest.ParallelManyThreadsAtSamePointTest) ... ok
test2 (bpmn.ParallelTest.ParallelManyThreadsAtSamePointTest) ... ok
test_breadth_first (bpmn.ParallelTest.ParallelManyThreadsAtSamePointTestNested) ... ok
test_depth_first (bpmn.ParallelTest.ParallelManyThreadsAtSamePointTestNested) ... ok
test1 (bpmn.ParallelTest.ParallelMultipleSplitsAndJoinsTest) ... ok
test2 (bpmn.ParallelTest.ParallelMultipleSplitsAndJoinsTest) ... ok
test3 (bpmn.ParallelTest.ParallelMultipleSplitsAndJoinsTest) ... ok
test4 (bpmn.ParallelTest.ParallelMultipleSplitsAndJoinsTest) ... ok
testRunThroughAlternating (bpmn.ParallelTest.ParallelMultipleSplitsTest) ... ok
testRunThroughChoiceFirst (bpmn.ParallelTest.ParallelOnePathEndsTest) ... ok
testRunThroughParallelTaskFirst (bpmn.ParallelTest.ParallelOnePathEndsTest) ... ok
testRunThroughParallelTaskFirstYes (bpmn.ParallelTest.ParallelOnePathEndsTest) ... ok
testRunThroughChoiceFirst (bpmn.ParallelTest.ParallelThenExlusiveNoInclusiveTest) ... ok
testRunThroughChoiceThreadCompleteFirst (bpmn.ParallelTest.ParallelThenExlusiveNoInclusiveTest) ... ok
testRunThroughParallelTaskFirst (bpmn.ParallelTest.ParallelThenExlusiveNoInclusiveTest) ... ok
testRunThroughChoiceFirst (bpmn.ParallelTest.ParallelThenExlusiveTest) ... ok
testRunThroughChoiceThreadCompleteFirst (bpmn.ParallelTest.ParallelThenExlusiveTest) ... ok
testRunThroughParallelTaskFirst (bpmn.ParallelTest.ParallelThenExlusiveTest) ... ok
testNoRouteNoFirstThenRepeating (bpmn.ParallelTest.ParallelThroughSameTaskTest) ... ok
testNoRouteNoTaskFirst (bpmn.ParallelTest.ParallelThroughSameTaskTest) ... ok
testNoRouteRepeatTaskFirst (bpmn.ParallelTest.ParallelThroughSameTaskTest) ... ok
testRepeatTasksReadyTogether (bpmn.ParallelTest.ParallelThroughSameTaskTest) ... ok
testRepeatTasksReadyTogetherSaveRestore (bpmn.ParallelTest.ParallelThroughSameTaskTest) ... ok
testRunThroughFirstRepeatTaskFirst (bpmn.ParallelTest.ParallelThroughSameTaskTest) ... ok
testRunThroughHappy (bpmn.TimerIntermediateTest.TimerIntermediateTest) ... ok
testAncestors (specs.ExecuteTest.ExecuteTest) ... ok
testConnect (specs.ExecuteTest.ExecuteTest) ... ok
testConstructor (specs.ExecuteTest.ExecuteTest) ... ok
testFollow (specs.ExecuteTest.ExecuteTest) ... ok
testGetData (specs.ExecuteTest.ExecuteTest) ... ok
testPattern (specs.ExecuteTest.ExecuteTest) ... ok
testSerialize (specs.ExecuteTest.ExecuteTest) ... ok
testSetData (specs.ExecuteTest.ExecuteTest) ... ok
testTest (specs.ExecuteTest.ExecuteTest) ... ok
test_ancestors_cyclic (specs.ExecuteTest.ExecuteTest) ... ok
testAncestors (specs.JoinTest.JoinTest) ... ok
testConnect (specs.JoinTest.JoinTest) ... ok
testConstructor (specs.JoinTest.JoinTest) ... ok
testFollow (specs.JoinTest.JoinTest) ... ok
testGetData (specs.JoinTest.JoinTest) ... ok
testSerialize (specs.JoinTest.JoinTest) ... ok
testSetData (specs.JoinTest.JoinTest) ... ok
testTest (specs.JoinTest.JoinTest) ... ok
test_ancestors_cyclic (specs.JoinTest.JoinTest) ... ok
testAncestors (specs.MergeTest.MergeTest) ... ok
testConnect (specs.MergeTest.MergeTest) ... ok
testConstructor (specs.MergeTest.MergeTest) ... ok
testFollow (specs.MergeTest.MergeTest) ... ok
testGetData (specs.MergeTest.MergeTest) ... ok
testSerialize (specs.MergeTest.MergeTest) ... ok
testSetData (specs.MergeTest.MergeTest) ... ok
testTest (specs.MergeTest.MergeTest) ... ok
test_Merge_data_merging (specs.MergeTest.MergeTest)
Test that Merge task actually merges data ... FAIL
test_ancestors_cyclic (specs.MergeTest.MergeTest) ... ok
testConstructor (specs.SubWorkflowTest.TaskSpecTest) ... ok
testSerialize (specs.SubWorkflowTest.TaskSpecTest) ... ok
testTest (specs.SubWorkflowTest.TaskSpecTest) ... ok
test_block_to_subworkflow (specs.SubWorkflowTest.TaskSpecTest) ... ok
test_subworkflow_to_block (specs.SubWorkflowTest.TaskSpecTest) ... ok
test_subworkflow_to_join (specs.SubWorkflowTest.TaskSpecTest) ... ok
test_subworkflow_to_join_refresh_waiting (specs.SubWorkflowTest.TaskSpecTest) ... ok
testAncestors (specs.TaskSpecTest.TaskSpecTest) ... ok
testConnect (specs.TaskSpecTest.TaskSpecTest) ... ok
testConstructor (specs.TaskSpecTest.TaskSpecTest) ... ok
testFollow (specs.TaskSpecTest.TaskSpecTest) ... ok
testGetData (specs.TaskSpecTest.TaskSpecTest) ... ok
testSerialize (specs.TaskSpecTest.TaskSpecTest) ... ok
testSetData (specs.TaskSpecTest.TaskSpecTest) ... ok
testTest (specs.TaskSpecTest.TaskSpecTest) ... ok
test_ancestors_cyclic (specs.TaskSpecTest.TaskSpecTest) ... ok
testAncestors (specs.TransformTest.TransformTest) ... ok
testConnect (specs.TransformTest.TransformTest) ... ok
testConstructor (specs.TransformTest.TransformTest) ... ok
testFollow (specs.TransformTest.TransformTest) ... ok
testGetData (specs.TransformTest.TransformTest) ... ok
testPattern (specs.TransformTest.TransformTest) ... ok
testSerialize (specs.TransformTest.TransformTest) ... ok
testSetData (specs.TransformTest.TransformTest) ... ok
testTest (specs.TransformTest.TransformTest) ... ok
test_ancestors_cyclic (specs.TransformTest.TransformTest) ... ok
testConstructor (specs.WorkflowSpecTest.WorkflowSpecTest) ... ok
testDump (specs.WorkflowSpecTest.WorkflowSpecTest) ... ok
testGetDump (specs.WorkflowSpecTest.WorkflowSpecTest) ... ok
testGetTaskSpecFromName (specs.WorkflowSpecTest.WorkflowSpecTest) ... ok
testSerialize (specs.WorkflowSpecTest.WorkflowSpecTest) ... ok
testValidate (specs.WorkflowSpecTest.WorkflowSpecTest) ... ok
testConstructor (storage.DictionarySerializerTest.DictionarySerializerTest) ... ok
testDeserializeWorkflow (storage.DictionarySerializerTest.DictionarySerializerTest) ... ok
testDeserializeWorkflowSpec (storage.DictionarySerializerTest.DictionarySerializerTest) ... ok
testSerializeWorkflow (storage.DictionarySerializerTest.DictionarySerializerTest) ... ERROR
testSerializeWorkflowSpec (storage.DictionarySerializerTest.DictionarySerializerTest) ... ok
testPattern (storage.DictionarySerializerTest.DictionarySerializeEveryPatternTest) ... C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\acyclic_synchronizing_merge.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\arbitrary_cycles.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\blocking_discriminator.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\blocking_partial_join.xml
ERROR
testConstructor (storage.JSONSerializerTest.JSONSerializerTest) ... ok
testDeserializeWorkflow (storage.JSONSerializerTest.JSONSerializerTest) ... ok
testDeserializeWorkflowSpec (storage.JSONSerializerTest.JSONSerializerTest) ... ok
testSerializeWorkflow (storage.JSONSerializerTest.JSONSerializerTest) ... ok
testSerializeWorkflowSpec (storage.JSONSerializerTest.JSONSerializerTest) ... ok
testPattern (storage.JSONSerializerTest.JSONSerializeEveryPatternTest) ... C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\acyclic_synchronizing_merge.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\arbitrary_cycles.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\blocking_discriminator.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\blocking_partial_join.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\cancelling_discriminator.xml
C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\data/spiff/control-flow\cancelling_partial_join.xml
ERROR
testConstructor (storage.OpenWfeXmlSerializerTest.OpenWfeXmlSerializerTest) ... ok
testDeserializeWorkflow (storage.OpenWfeXmlSerializerTest.OpenWfeXmlSerializerTest) ... ok
testDeserializeWorkflowSpec (storage.OpenWfeXmlSerializerTest.OpenWfeXmlSerializerTest) ... FAIL
testSerializeWorkflow (storage.OpenWfeXmlSerializerTest.OpenWfeXmlSerializerTest) ... ok
testSerializeWorkflowSpec (storage.OpenWfeXmlSerializerTest.OpenWfeXmlSerializerTest) ... ok
testConstructor (storage.SerializerTest.SerializerTest) ... ok
testDeserializeWorkflow (storage.SerializerTest.SerializerTest) ... ok
testDeserializeWorkflowSpec (storage.SerializerTest.SerializerTest) ... ok
testSerializeWorkflow (storage.SerializerTest.SerializerTest) ... ok
testSerializeWorkflowSpec (storage.SerializerTest.SerializerTest) ... ok
testConstructor (storage.XmlSerializerTest.XmlSerializerTest) ... ok
testDeserializeWorkflow (storage.XmlSerializerTest.XmlSerializerTest) ... ok
testDeserializeWorkflowSpec (storage.XmlSerializerTest.XmlSerializerTest) ... ok
testSerializeWorkflow (storage.XmlSerializerTest.XmlSerializerTest) ... ok
testSerializeWorkflowSpec (storage.XmlSerializerTest.XmlSerializerTest) ... ok

======================================================================
ERROR: testSerializeWorkflow (storage.DictionarySerializerTest.DictionarySerializerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\storage\SerializerTest.py", line 123, in testSerializeWorkflow
    exclude_dynamic=True)
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\storage\DictionarySerializerTest.py", line 43, in compareSerialization
    raise Exception(key + '/' + str(e))
Exception: data/synch_1_reached/Unequal: 'gAJLAS4=' vs 'gAJLAi4='

======================================================================
ERROR: testPattern (storage.DictionarySerializerTest.DictionarySerializeEveryPatternTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\PatternTest.py", line 62, in testPattern
    self.run_pattern(filename)
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\storage\SerializerTest.py", line 158, in run_pattern
    data=expected_data)
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\storage\SerializerTest.py", line 123, in testSerializeWorkflow
    exclude_dynamic=True)
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\storage\DictionarySerializerTest.py", line 43, in compareSerialization
    raise Exception(key + '/' + str(e))
Exception: data/struct_synch_merge_1_reached/Unequal: 'gAJLAi4=' vs 'gAJLBC4='

======================================================================
ERROR: testPattern (storage.JSONSerializerTest.JSONSerializeEveryPatternTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\PatternTest.py", line 62, in testPattern
    self.run_pattern(filename)
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\storage\SerializerTest.py", line 158, in run_pattern
    data=expected_data)
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\storage\SerializerTest.py", line 123, in testSerializeWorkflow
    exclude_dynamic=True)
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\storage\JSONSerializerTest.py", line 36, in compareSerialization
    exclude_items=exclude_items)
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\storage\DictionarySerializerTest.py", line 43, in compareSerialization
    raise Exception(key + '/' + str(e))
Exception: data/struct_synch_merge_1_reached/Unequal: u'gAJLAi4=' vs u'gAJLBC4='

======================================================================
FAIL: test_Merge_data_merging (specs.MergeTest.MergeTest)
Test that Merge task actually merges data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\specs\MergeTest.py", line 68, in test_Merge_data_merging
    self.assert_('second' in task.data)
AssertionError: False is not true

======================================================================
FAIL: testDeserializeWorkflowSpec (storage.OpenWfeXmlSerializerTest.OpenWfeXmlSerializerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\storage\OpenWfeXmlSerializerTest.py", line 38, in testDeserializeWorkflowSpec
    run_workflow(self, wf_spec, path, None)
  File "C:\ACME\Dev\projects\SpiffWorkflow-master_GITHUB2\tests\SpiffWorkflow\util.py", line 110, in run_workflow
    test.assert_(taken_path == expected_path, error)
AssertionError: Expected:
Start
  concurrence_1
    task_a1
      task_a2
        if_condition_1
          task_a3
            if_condition_1_end
              if_condition_2
                task_a5
                  if_condition_2_end
    task_b1
      task_b2
        concurrence_1_end
          task_c1
            task_c2
              End

but got:
Start
  concurrence_1
    task_a1
      task_a2
        if_condition_1
          task_a3
            if_condition_1_end
              if_condition_2
                task_a5
                  if_condition_2_end
    task_b1
      task_b2
                    concurrence_1_end
                      task_c1
                        task_c2
                          End



----------------------------------------------------------------------
Ran 161 tests in 12.789s

FAILED (failures=2, errors=3)

Process finished with exit code 1
```

**Comment by knipknap** [comment]
Sorry I can't help with that; I don't have a windows machine to test with. Patches are welcome though!
